/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as FormIdRouteImport } from './routes/$formId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubmitRouteImport } from './routes/api/submit'
import { Route as ApiLlmProxyRouteImport } from './routes/api/llm-proxy'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiExportFacetIdRouteImport } from './routes/api/export/$facetId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedBuildFacetIdRouteImport } from './routes/_authed/build/$facetId'
import { Route as ApiExportZipFormIdRouteImport } from './routes/api/export/zip/$formId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const FormIdRoute = FormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitRoute = ApiSubmitRouteImport.update({
  id: '/api/submit',
  path: '/api/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmProxyRoute = ApiLlmProxyRouteImport.update({
  id: '/api/llm-proxy',
  path: '/api/llm-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiExportFacetIdRoute = ApiExportFacetIdRouteImport.update({
  id: '/api/export/$facetId',
  path: '/api/export/$facetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBuildFacetIdRoute = AuthedBuildFacetIdRouteImport.update({
  id: '/build/$facetId',
  path: '/build/$facetId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiExportZipFormIdRoute = ApiExportZipFormIdRouteImport.update({
  id: '/api/export/zip/$formId',
  path: '/api/export/zip/$formId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$formId': typeof FormIdRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/llm-proxy': typeof ApiLlmProxyRoute
  '/api/submit': typeof ApiSubmitRoute
  '/build/$facetId': typeof AuthedBuildFacetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/$facetId': typeof ApiExportFacetIdRoute
  '/api/export/zip/$formId': typeof ApiExportZipFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$formId': typeof FormIdRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/llm-proxy': typeof ApiLlmProxyRoute
  '/api/submit': typeof ApiSubmitRoute
  '/build/$facetId': typeof AuthedBuildFacetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/$facetId': typeof ApiExportFacetIdRoute
  '/api/export/zip/$formId': typeof ApiExportZipFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$formId': typeof FormIdRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/api/llm-proxy': typeof ApiLlmProxyRoute
  '/api/submit': typeof ApiSubmitRoute
  '/_authed/build/$facetId': typeof AuthedBuildFacetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/$facetId': typeof ApiExportFacetIdRoute
  '/api/export/zip/$formId': typeof ApiExportZipFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$formId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/api/llm-proxy'
    | '/api/submit'
    | '/build/$facetId'
    | '/api/auth/$'
    | '/api/export/$facetId'
    | '/api/export/zip/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$formId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/api/llm-proxy'
    | '/api/submit'
    | '/build/$facetId'
    | '/api/auth/$'
    | '/api/export/$facetId'
    | '/api/export/zip/$formId'
  id:
    | '__root__'
    | '/'
    | '/$formId'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/api/llm-proxy'
    | '/api/submit'
    | '/_authed/build/$facetId'
    | '/api/auth/$'
    | '/api/export/$facetId'
    | '/api/export/zip/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormIdRoute: typeof FormIdRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiLlmProxyRoute: typeof ApiLlmProxyRoute
  ApiSubmitRoute: typeof ApiSubmitRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExportFacetIdRoute: typeof ApiExportFacetIdRoute
  ApiExportZipFormIdRoute: typeof ApiExportZipFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$formId': {
      id: '/$formId'
      path: '/$formId'
      fullPath: '/$formId'
      preLoaderRoute: typeof FormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit': {
      id: '/api/submit'
      path: '/api/submit'
      fullPath: '/api/submit'
      preLoaderRoute: typeof ApiSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-proxy': {
      id: '/api/llm-proxy'
      path: '/api/llm-proxy'
      fullPath: '/api/llm-proxy'
      preLoaderRoute: typeof ApiLlmProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/export/$facetId': {
      id: '/api/export/$facetId'
      path: '/api/export/$facetId'
      fullPath: '/api/export/$facetId'
      preLoaderRoute: typeof ApiExportFacetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/build/$facetId': {
      id: '/_authed/build/$facetId'
      path: '/build/$facetId'
      fullPath: '/build/$facetId'
      preLoaderRoute: typeof AuthedBuildFacetIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/export/zip/$formId': {
      id: '/api/export/zip/$formId'
      path: '/api/export/zip/$formId'
      fullPath: '/api/export/zip/$formId'
      preLoaderRoute: typeof ApiExportZipFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedBuildFacetIdRoute: typeof AuthedBuildFacetIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedBuildFacetIdRoute: AuthedBuildFacetIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormIdRoute: FormIdRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiLlmProxyRoute: ApiLlmProxyRoute,
  ApiSubmitRoute: ApiSubmitRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExportFacetIdRoute: ApiExportFacetIdRoute,
  ApiExportZipFormIdRoute: ApiExportZipFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
